### ISSUE TITLE
Italics on indent symbol

### ISSUE THREAD

**Issue by ghost** [drazil100/dusklight.vim#2]
Hi there, love this color scheme, but have one problem.
The indent line seems to be in italics for me, giving a weird look (see attached),
I am using indent-blankline.nvim with the default config of lazyvim.

![screenshot](https://github.com/user-attachments/assets/802c205e-d43b-460a-87c3-4e2fa93da8fc)

**Comment by drazil100** [comment]
Huh weird. I don't know why I had it set that way. Probably a remnent of https://bytefluent.com/vivify/. I checked a couple other themes and best I could tell they don't italic this character so I went ahead and changed it in [ff75f79](https://github.com/drazil100/dusklight.vim/commit/ff75f79734d7e0e350e2154c0db005a4eec81df8).

**Comment by ghost** [comment]
Seems like you almost there, but there must be another place too. as can be seen from attached.

![screenshot-2024-09-21-05-13-54](https://github.com/user-attachments/assets/af83cb6f-7554-4e7c-96a5-c7ea1b6b9496)

**Comment by drazil100** [comment]
Weird. Every place this color shows up in my code is set to NONE instead of italic.

It looks as though from the code you shared that whatever plugin you are using is applying it on top of commented text which is italic... Not entirely sure how to resolve this as I like the comment text italic.

Could you by chance open the file in the screenshot and then run this command?
`:redir @">|silent hi|redir END|tabedit|put`

This command will dump the output of highlight (which lists all highlights you have set) directly into the buffer rather than showing them as normal command output. From there you can send me a list of all your highlights and I can see what is setting the coloring for those characters. Opening the file from the screenshot first is just to make 100% sure that the highlights causing this are loaded.

Also if you have the name for this plugin it will make finding it in the list easier.

**Comment by ghost** [comment]
Lols, talk about wierd, I narrowed it down to terminal emulator if you can believe!
See attached - same file, Left is Wezterm, right is Cosmic-term. 
Seeing as cosmic is still alpha, lets leave it at that! Laugh, enjoy your weekend! :-D

![screenshot-2024-09-21-14-04-15](https://github.com/user-attachments/assets/d554f5f3-e05a-44cf-b7c8-a8a2fec5f9ba)

**Comment by drazil100** [comment]
NICE! I'm also daily driving cosmic right now!

While a random GitHub issue probably isn't the place for plugs (who cares it's my repo imma do it anyway) I do have a cosmic dusklight theme
https://cosmic-themes.org/53/

I also have a Firefox theme
https://addons.mozilla.org/en-US/firefox/addon/dusklight/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

And dusklight is built into btop++/bpytop

Anyway back on subject, what plugin do you have that is generating those highlights on the comments? Do you know? While I can't promise to be able to fix it (cause you are probably right that it's the terminal) I can at least poke around in cosmic-term. The list of highlights would also be helpful. 

If I can't fix it I can maybe submit it as a bug report elsewhere.

**Comment by ghost** [comment]
Awesome - sporting new new desktop/firefox themes!
Wrt the comments, I'm not noticing anything unusual in them - what hi are you talking about (feeling dumb)? 
Anyway, [my config](https://github.com/russ-dm/nvim) if you want to have a look at the config.
